/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inmobiliaria.vistas.vistasContrato;

import java.awt.Color;

/**
 *
 * @author nican
 */
public class ContratoMenu extends javax.swing.JPanel {

    
        
    Color lightblue = new Color(54,135,195);
    Color blue = new Color(0,63,121);
    /**
     * Creates new form ContratoMenu
     */
    public ContratoMenu() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenuContrato = new javax.swing.JPanel();
        jpEditarContrato = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpEliminarContrato = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpAgregarContrato = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpBuscarContrato = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jpEditarContrato.setBackground(new java.awt.Color(54, 135, 195));
        jpEditarContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpEditarContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEditarContratoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpEditarContratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpEditarContratoMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editar");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contrato");

        javax.swing.GroupLayout jpEditarContratoLayout = new javax.swing.GroupLayout(jpEditarContrato);
        jpEditarContrato.setLayout(jpEditarContratoLayout);
        jpEditarContratoLayout.setHorizontalGroup(
            jpEditarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpEditarContratoLayout.setVerticalGroup(
            jpEditarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jpEliminarContrato.setBackground(new java.awt.Color(54, 135, 195));
        jpEliminarContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpEliminarContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEliminarContratoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpEliminarContratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpEliminarContratoMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eliminar");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contrato");

        javax.swing.GroupLayout jpEliminarContratoLayout = new javax.swing.GroupLayout(jpEliminarContrato);
        jpEliminarContrato.setLayout(jpEliminarContratoLayout);
        jpEliminarContratoLayout.setHorizontalGroup(
            jpEliminarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEliminarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpEliminarContratoLayout.setVerticalGroup(
            jpEliminarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jpAgregarContrato.setBackground(new java.awt.Color(54, 135, 195));
        jpAgregarContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAgregarContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAgregarContratoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpAgregarContratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAgregarContratoMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contrato");

        javax.swing.GroupLayout jpAgregarContratoLayout = new javax.swing.GroupLayout(jpAgregarContrato);
        jpAgregarContrato.setLayout(jpAgregarContratoLayout);
        jpAgregarContratoLayout.setHorizontalGroup(
            jpAgregarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAgregarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpAgregarContratoLayout.setVerticalGroup(
            jpAgregarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jpBuscarContrato.setBackground(new java.awt.Color(54, 135, 195));
        jpBuscarContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBuscarContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBuscarContratoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBuscarContratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBuscarContratoMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contrato");

        javax.swing.GroupLayout jpBuscarContratoLayout = new javax.swing.GroupLayout(jpBuscarContrato);
        jpBuscarContrato.setLayout(jpBuscarContratoLayout);
        jpBuscarContratoLayout.setHorizontalGroup(
            jpBuscarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpBuscarContratoLayout.setVerticalGroup(
            jpBuscarContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarContratoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpMenuContratoLayout = new javax.swing.GroupLayout(jpMenuContrato);
        jpMenuContrato.setLayout(jpMenuContratoLayout);
        jpMenuContratoLayout.setHorizontalGroup(
            jpMenuContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuContratoLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jpMenuContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAgregarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpBuscarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jpMenuContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpEditarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEliminarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        jpMenuContratoLayout.setVerticalGroup(
            jpMenuContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuContratoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jpMenuContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAgregarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEditarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jpMenuContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBuscarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEliminarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenuContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenuContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpEditarContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEditarContratoMouseClicked
        // TODO add your handling code here:
        jpMenuContrato.removeAll();

        EditarContrato editContratoMenu = new EditarContrato();
        editContratoMenu.setSize(530, 410);
        editContratoMenu.setLocation(0, 0);

        jpMenuContrato.add(editContratoMenu);
        jpMenuContrato.revalidate();
    }//GEN-LAST:event_jpEditarContratoMouseClicked

    private void jpEditarContratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEditarContratoMouseEntered
        // TODO add your handling code here:
        jpEditarContrato.setBackground(blue);
    }//GEN-LAST:event_jpEditarContratoMouseEntered

    private void jpEditarContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEditarContratoMouseExited
        // TODO add your handling code here:
        jpEditarContrato.setBackground(lightblue);
    }//GEN-LAST:event_jpEditarContratoMouseExited

    private void jpEliminarContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarContratoMouseClicked
        // TODO add your handling code here:
        jpMenuContrato.removeAll();

        EliminarContrato eliminarContratoMenu = new EliminarContrato();
        eliminarContratoMenu.setSize(530, 410);
        eliminarContratoMenu.setLocation(0, 0);

        jpMenuContrato.add(eliminarContratoMenu);
        jpMenuContrato.revalidate();
    }//GEN-LAST:event_jpEliminarContratoMouseClicked

    private void jpEliminarContratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarContratoMouseEntered
        // TODO add your handling code here:
        jpEliminarContrato.setBackground(blue);
    }//GEN-LAST:event_jpEliminarContratoMouseEntered

    private void jpEliminarContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarContratoMouseExited
        // TODO add your handling code here:
        jpEliminarContrato.setBackground(lightblue);
    }//GEN-LAST:event_jpEliminarContratoMouseExited

    private void jpAgregarContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarContratoMouseClicked
        // TODO add your handling code here:
        jpMenuContrato.removeAll();

        AgregarContrato nuevoContratoMenu = new AgregarContrato();
        nuevoContratoMenu.setSize(530, 410);
        nuevoContratoMenu.setLocation(0, 0);

        jpMenuContrato.add(nuevoContratoMenu);
        jpMenuContrato.revalidate();

    }//GEN-LAST:event_jpAgregarContratoMouseClicked

    private void jpAgregarContratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarContratoMouseEntered
        // TODO add your handling code here:
        jpAgregarContrato.setBackground(blue);
    }//GEN-LAST:event_jpAgregarContratoMouseEntered

    private void jpAgregarContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarContratoMouseExited
        // TODO add your handling code here:
        jpAgregarContrato.setBackground(lightblue);
    }//GEN-LAST:event_jpAgregarContratoMouseExited

    private void jpBuscarContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarContratoMouseClicked
        // TODO add your handling code here:
        jpMenuContrato.removeAll();

        BuscarContrato buscarContratoMenu = new BuscarContrato();
        buscarContratoMenu.setSize(530, 410);
        buscarContratoMenu.setLocation(0, 0);

        jpMenuContrato.add(buscarContratoMenu);
        jpMenuContrato.revalidate();
    }//GEN-LAST:event_jpBuscarContratoMouseClicked

    private void jpBuscarContratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarContratoMouseEntered
        // TODO add your handling code here:
        jpBuscarContrato.setBackground(blue);
    }//GEN-LAST:event_jpBuscarContratoMouseEntered

    private void jpBuscarContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarContratoMouseExited
        // TODO add your handling code here:
        jpBuscarContrato.setBackground(lightblue);
    }//GEN-LAST:event_jpBuscarContratoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpAgregarContrato;
    private javax.swing.JPanel jpBuscarContrato;
    private javax.swing.JPanel jpEditarContrato;
    private javax.swing.JPanel jpEliminarContrato;
    private javax.swing.JPanel jpMenuContrato;
    // End of variables declaration//GEN-END:variables
}
