/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inmobiliaria.vistas.vistasInquilino;

import java.awt.Color;

/**
 *
 * @author nican
 */
public class InquilinoMenu extends javax.swing.JPanel {

    /**
     * Creates new form InquilinoMenu
     */
    Color lightblue = new Color(54,135,195);
    Color blue = new Color(0,63,121);
    
    public InquilinoMenu() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInquilinoMenu = new javax.swing.JPanel();
        jpEliminarInquilino = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpAgregarInquilino = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpBuscarInquilino = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpEditarInquilino = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jpEliminarInquilino.setBackground(new java.awt.Color(54, 135, 195));
        jpEliminarInquilino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpEliminarInquilino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEliminarInquilinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpEliminarInquilinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpEliminarInquilinoMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eliminar");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inquilino");

        javax.swing.GroupLayout jpEliminarInquilinoLayout = new javax.swing.GroupLayout(jpEliminarInquilino);
        jpEliminarInquilino.setLayout(jpEliminarInquilinoLayout);
        jpEliminarInquilinoLayout.setHorizontalGroup(
            jpEliminarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEliminarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpEliminarInquilinoLayout.setVerticalGroup(
            jpEliminarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jpAgregarInquilino.setBackground(new java.awt.Color(54, 135, 195));
        jpAgregarInquilino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpAgregarInquilino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAgregarInquilinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpAgregarInquilinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpAgregarInquilinoMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inquilino");

        javax.swing.GroupLayout jpAgregarInquilinoLayout = new javax.swing.GroupLayout(jpAgregarInquilino);
        jpAgregarInquilino.setLayout(jpAgregarInquilinoLayout);
        jpAgregarInquilinoLayout.setHorizontalGroup(
            jpAgregarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAgregarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpAgregarInquilinoLayout.setVerticalGroup(
            jpAgregarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jpBuscarInquilino.setBackground(new java.awt.Color(54, 135, 195));
        jpBuscarInquilino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBuscarInquilino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBuscarInquilinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBuscarInquilinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBuscarInquilinoMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inquilino");

        javax.swing.GroupLayout jpBuscarInquilinoLayout = new javax.swing.GroupLayout(jpBuscarInquilino);
        jpBuscarInquilino.setLayout(jpBuscarInquilinoLayout);
        jpBuscarInquilinoLayout.setHorizontalGroup(
            jpBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpBuscarInquilinoLayout.setVerticalGroup(
            jpBuscarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jpEditarInquilino.setBackground(new java.awt.Color(54, 135, 195));
        jpEditarInquilino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpEditarInquilino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpEditarInquilinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpEditarInquilinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpEditarInquilinoMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editar");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Inquilino");

        javax.swing.GroupLayout jpEditarInquilinoLayout = new javax.swing.GroupLayout(jpEditarInquilino);
        jpEditarInquilino.setLayout(jpEditarInquilinoLayout);
        jpEditarInquilinoLayout.setHorizontalGroup(
            jpEditarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jpEditarInquilinoLayout.setVerticalGroup(
            jpEditarInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpInquilinoMenuLayout = new javax.swing.GroupLayout(jpInquilinoMenu);
        jpInquilinoMenu.setLayout(jpInquilinoMenuLayout);
        jpInquilinoMenuLayout.setHorizontalGroup(
            jpInquilinoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInquilinoMenuLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jpInquilinoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAgregarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpBuscarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jpInquilinoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpEditarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEliminarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        jpInquilinoMenuLayout.setVerticalGroup(
            jpInquilinoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInquilinoMenuLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jpInquilinoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAgregarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEditarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jpInquilinoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBuscarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEliminarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInquilinoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInquilinoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpEliminarInquilinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarInquilinoMouseClicked
        // TODO add your handling code here:
        jpInquilinoMenu.removeAll();

        EliminarInquilino eliminarInquiMenu = new EliminarInquilino();
        eliminarInquiMenu.setSize(530, 410);
        eliminarInquiMenu.setLocation(0, 0);

        jpInquilinoMenu.add(eliminarInquiMenu);
        jpInquilinoMenu.revalidate();
    }//GEN-LAST:event_jpEliminarInquilinoMouseClicked

    private void jpEliminarInquilinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarInquilinoMouseEntered
        // TODO add your handling code here:
        jpEliminarInquilino.setBackground(blue);
    }//GEN-LAST:event_jpEliminarInquilinoMouseEntered

    private void jpEliminarInquilinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEliminarInquilinoMouseExited
        // TODO add your handling code here:
        jpEliminarInquilino.setBackground(lightblue);
    }//GEN-LAST:event_jpEliminarInquilinoMouseExited

    private void jpAgregarInquilinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarInquilinoMouseClicked
        // TODO add your handling code here:
        jpInquilinoMenu.removeAll();

        AgregarInquilino nuevoInquiMenu = new AgregarInquilino();
        nuevoInquiMenu.setSize(530, 410);
        nuevoInquiMenu.setLocation(0, 0);

        jpInquilinoMenu.add(nuevoInquiMenu);
        jpInquilinoMenu.revalidate();

    }//GEN-LAST:event_jpAgregarInquilinoMouseClicked

    private void jpAgregarInquilinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarInquilinoMouseEntered
        // TODO add your handling code here:
        jpAgregarInquilino.setBackground(blue);
    }//GEN-LAST:event_jpAgregarInquilinoMouseEntered

    private void jpAgregarInquilinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAgregarInquilinoMouseExited
        // TODO add your handling code here:
        jpAgregarInquilino.setBackground(lightblue);
    }//GEN-LAST:event_jpAgregarInquilinoMouseExited

    private void jpBuscarInquilinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarInquilinoMouseClicked
        // TODO add your handling code here:
        jpInquilinoMenu.removeAll();

        BuscarInquilino buscarInquiMenu = new BuscarInquilino();
        buscarInquiMenu.setSize(530, 410);
        buscarInquiMenu.setLocation(0, 0);

        jpInquilinoMenu.add(buscarInquiMenu);
        jpInquilinoMenu.revalidate();
    }//GEN-LAST:event_jpBuscarInquilinoMouseClicked

    private void jpBuscarInquilinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarInquilinoMouseEntered
        // TODO add your handling code here:
        jpBuscarInquilino.setBackground(blue);
    }//GEN-LAST:event_jpBuscarInquilinoMouseEntered

    private void jpBuscarInquilinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBuscarInquilinoMouseExited
        // TODO add your handling code here:
        jpBuscarInquilino.setBackground(lightblue);
    }//GEN-LAST:event_jpBuscarInquilinoMouseExited

    private void jpEditarInquilinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEditarInquilinoMouseClicked
        // TODO add your handling code here:
        jpInquilinoMenu.removeAll();

        EditarInquilino editInquiMenu = new EditarInquilino();
        editInquiMenu.setSize(530, 410);
        editInquiMenu.setLocation(0, 0);

        jpInquilinoMenu.add(editInquiMenu);
        jpInquilinoMenu.revalidate();
    }//GEN-LAST:event_jpEditarInquilinoMouseClicked

    private void jpEditarInquilinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEditarInquilinoMouseEntered
        // TODO add your handling code here:
        jpEditarInquilino.setBackground(blue);
    }//GEN-LAST:event_jpEditarInquilinoMouseEntered

    private void jpEditarInquilinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpEditarInquilinoMouseExited
        // TODO add your handling code here:
        jpEditarInquilino.setBackground(lightblue);
    }//GEN-LAST:event_jpEditarInquilinoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpAgregarInquilino;
    private javax.swing.JPanel jpBuscarInquilino;
    private javax.swing.JPanel jpEditarInquilino;
    private javax.swing.JPanel jpEliminarInquilino;
    private javax.swing.JPanel jpInquilinoMenu;
    // End of variables declaration//GEN-END:variables
}
